version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: crypto_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql

volumes:
  mariadb_data:
